name: Publish to Zapier

on:
  workflow_run:
    workflows: [Test]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends jq

      - name: Install Zapier CLI
        run: npm install --global zapier-platform-cli

      - name: Login to Zapier by writing the API Key to a file
        run: |
          echo '{"deployKey": "${{ secrets.DEPLOY_KEY }}"}' | jq > ${{ runner.temp }}/auth.json

      - name: Build and Push Integration Code to Zapier
        run: ZAPIER_AUTH_LOCATION=${{ runner.temp }}/auth.json zapier push
